# Generated by Django 6.1.1 on 2026-09-17 11:25
#
# Troca a relação many-to-one (Note.tag) pela many-to-many (Note.tags).
# A ordem importa: o campo novo é criado primeiro, os dados são copiados
# e só então a chave estrangeira antiga é removida — assim nenhuma
# associação entre anotação e tag se perde no caminho.

from django.db import migrations, models


def copiar_tag_para_tags(apps, schema_editor):
    """Leva a tag única de cada anotação para a nova relação many-to-many."""
    Note = apps.get_model('notes', 'Note')
    for note in Note.objects.exclude(tag__isnull=True):
        note.tags.add(note.tag)


def copiar_tags_para_tag(apps, schema_editor):
    """Volta atrás: guarda a primeira tag de cada anotação na chave estrangeira."""
    Note = apps.get_model('notes', 'Note')
    for note in Note.objects.all():
        primeira = note.tags.first()
        if primeira is not None:
            note.tag = primeira
            note.save(update_fields=['tag'])


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_note_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.tag'),
        ),
        migrations.RunPython(copiar_tag_para_tags, copiar_tags_para_tag),
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
    ]
